//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectBDStudent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public string Nume { get; set; }
        public string Adresa { get; set; }
        public string CNP { get; set; }
        public Nullable<int> CodS { get; set; }
        public Nullable<double> Bursa { get; set; }
    }
}
